import { motion } from "framer-motion";
import { Building2, Lightbulb, IndianRupee, Users, FlaskConical, Scale } from "lucide-react";

const benefits = [
  {
    icon: Building2,
    title: "Infrastructure at Scale",
    description: "7,000 sq. ft. of dedicated startup space with 8 Centres of Excellence and 25+ specialized prototyping labs.",
  },
  {
    icon: IndianRupee,
    title: "Funding Impact",
    description: "₹75+ Lakh in institutional support and ₹80+ Lakh YTD revenue generated by incubated startups.",
  },
  {
    icon: Users,
    title: "Alumni Support Network",
    description: "Direct access to successful alumni entrepreneurs for guidance, playbooks, and market introductions.",
  },
  {
    icon: Lightbulb,
    title: "Expert Faculty Mentorship",
    description: "Dedicated academic and technical mentorship from distinguished faculty across engineering and business domains.",
  },
  {
    icon: Scale,
    title: "Legal & IP Support",
    description: "Comprehensive support for intellectual property, compliance, and legal structuring with access to a dedicated legal advisor.",
  },
  {
    icon: FlaskConical,
    title: "Prototyping Ecosystem",
    description: "A broad prototyping backbone for hardware and deep-tech ventures, enabling rapid testing and product iteration.",
  },
];

const stats = [
  { value: "26+", label: "Active Startups" },
  { value: "₹75L+", label: "Institutional Funding" },
  { value: "₹80L+", label: "YTD Revenue" },
  { value: "7,000", label: "Sq. Ft. Infrastructure" },
];

const IncubationBenefits = () => {
  return (
    <section className="px-6 py-24 md:px-12 lg:px-20 bg-secondary/30" id="benefits">
      <div className="max-w-[1400px] mx-auto">
        <div className="mb-16">
          <p className="font-mono-ui text-muted-foreground uppercase tracking-widest mb-4">Why Build Here</p>
          <h2 className="font-season-mix text-4xl md:text-6xl text-foreground">
            Built for Builders
          </h2>
          <p className="mt-6 text-lg text-muted-foreground max-w-2xl leading-relaxed">
            The incubation program combines strong infrastructure, strategic mentorship,
            legal support, and a high-trust founder network to help startups move faster.
          </p>
        </div>

        {/* Stats row */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, ease: [0.19, 1, 0.22, 1] }}
          className="grid grid-cols-2 md:grid-cols-4 gap-[1px] bg-border mb-16"
        >
          {stats.map((stat) => (
            <div key={stat.label} className="bg-card p-8 text-center">
              <p className="font-season-mix text-3xl md:text-4xl text-foreground">{stat.value}</p>
              <p className="font-mono-ui text-muted-foreground mt-2">{stat.label}</p>
            </div>
          ))}
        </motion.div>

        {/* Benefits grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[1px] bg-border">
          {benefits.map((benefit, i) => (
            <motion.div
              key={benefit.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-30px" }}
              transition={{
                duration: 0.5,
                delay: i * 0.06,
                ease: [0.19, 1, 0.22, 1],
              }}
              className="bg-card p-8 md:p-10"
            >
              <benefit.icon className="w-6 h-6 text-accent mb-5" strokeWidth={1.5} />
              <h3 className="text-lg font-semibold text-foreground mb-3">{benefit.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{benefit.description}</p>
            </motion.div>
          ))}
        </div>

        {/* Coordinator */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-16 pt-8 border-t border-border"
        >
          <p className="font-mono-ui text-muted-foreground uppercase tracking-widest mb-2">Coordinator</p>
          <p className="text-xl font-semibold text-foreground">Dr. Manish Sharma</p>
          <p className="text-sm text-muted-foreground mt-1">
            Institute Innovation and Incubation Coordinator · In-charge, DYPEC Dnyansagar Incubation Hub
          </p>
        </motion.div>
      </div>
    </section>
  );
};

export default IncubationBenefits;
